training_proj/training_proj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from scraper import views as scraper_views
from chatbot import views as bot_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('scraper/', scraper_views.scraperlink, name='scraper'),
    path('scraperdata/', scraper_views.scraperdataview, name='scraperdata'),
    path('', scraper_views.scraperdash, name='home'),
    path('accounts/',include('allauth.urls')),
    path('webhook/', bot_views.webhook, name='webhook'),
    path('data/', scraper_views.pivot_data, name='pivot_data'),
    path('reviewstats/', scraper_views.reviewstats, name='reviewstats'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

training_proj/scraper/models.py
from django.db import models


# Create your models here.

class ScrapedData(models.Model):
    airline_name = models.CharField(max_length=100)
    biz_model = models.CharField(max_length=100)
    network = models.CharField(max_length=100)
    group = models.CharField(max_length=100)
    hub = models.CharField(max_length=100)
    territory = models.CharField(max_length=100)
    address = models.CharField(max_length=1000)
    iata_code = models.CharField(max_length=50)
    icao_code = models.CharField(max_length=50)
    about = models.CharField(max_length=10000)
    ranking = models.CharField(max_length=50)
    prevrank = models.CharField(max_length=50)
    ratingval = models.CharField(max_length=50)
    image_url = models.CharField(max_length=500,default='default.jpg')
    site_url = models.CharField(max_length=500,default='www.ibsplc.com')
    source_url=models.CharField(max_length=500,default='www.ibsplc.com')


class ScrapeLinks(models.Model):
    airline_name = models.CharField(max_length=100)
    link = models.CharField(max_length=1000)
    review_url = models.CharField(max_length=1000,default='https://www.airlinequality.com/review-pages/a-z-airline-reviews/')
    image_url = models.CharField(max_length=5000,default='default.jpg')


class ScrapedReviewData(models.Model):
    airline_name = models.CharField(max_length=100)
    polarity = models.CharField(max_length=100)
    subjectivity = models.CharField(max_length=100)

training_proj/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super().save()
        img = Image.open(self.image.path)

        if img.height > 300 or img.width >300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

training_proj/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =['image']

training_proj/users/views.py
from django.shortcuts import render,redirect
from django.contrib import  messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm as ucf,ProfileUpdateForm,UserUpdateForm

# Create your views here.

def register(request) :
    if request.method == 'POST':
        form = ucf(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Your account has been created!')
            return redirect('login')
    else:
        form = ucf()
    return render(request, 'users/register.html', {'form': form})

def home(request) :
    return render(request,'users/home.html')


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form':u_form,
        'p_form':p_form
    }
    return render(request,'users/profile.html', context)

training_proj/users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/500733f512.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{%static 'css/bootstrap-social.css'%}">
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<!--    <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">-->
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home'%}">
        Scraper</a>

   {% if perms.scraper.change_scrapelinks %}
    <a class="nav-item nav-link" href="{% url 'scraper'%}">Add Scrape Links</a>
    <a class="nav-item nav-link" href="{% url 'scraperdata'%}">View Scrape Data</a>
    {%endif%}
  {%if user.is_authenticated%}
    <a class="nav-item nav-link" href="{% url 'reviewstats'%}">View Scraped Review Statistics</a>
     {%endif%}


  <div class="collapse navbar-collapse" >

  </div>
    <div class="navbar-nav">
      {%if user.is_authenticated%}
      {%if request.path != '/profile/'%}
      <a class="nav-item nav-link" href="{% url 'profile'%}"><img class="rounded-circle" src="{{user.profile.image.url}}" style="height: 35px;
  width: 35px;
  margin-right: 5px;">Hi,{{user.get_username}}!</a>
      {%endif%}
      <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
      {% else %}
      <a class="nav-item nav-link" href="{% url 'login'%}">Login</a>
      <a class="nav-item nav-link" href="{% url 'register'%}">Sign Up</a>
      {% endif %}
    </div>
</nav>
    <div class="container">
      {% if messages %}
      {% for message in messages%}
      <div class="alert alert-{{message.tags}}">
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
    {%block content%}
      {%endblock%}
    </div>
  </body>
</html>

training_proj/users/templates/users/home.html
{%extends "users/base.html"%}
{%block content%}
<h1>home</h1>
<a href="{{register}}">register</a>
{%endblock%}

training_proj/users/templates/users/login.html
{%extends "users/base.html"%}
{%load crispy_forms_tags%}
{%load socialaccount%}
{%providers_media_js%}
{%block content%}
<div class="jumbotron float-md-center mt-5">
<!--    col-lg-6 col-md-6 col-sm-6 col-xs-6 offset-3 -->
<form method="post">
    {%csrf_token%}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Log In</legend>
    {{form|crispy}}
    </fieldset>
    <button class="btn btn-primary" type="submit">Login</button>
</form>
    <small class="text-muted mt-2">&nbsp&nbsp&nbsp&nbsp&nbsp&nbspor</small><br>
    <a class="btn  btn-social btn-google mt-2" href="{% provider_login_url "google" %}">
    <span class="fa fa-google"></span> Sign in with Google
    </a>
<div class="border-top pt-3">
    <small class="text-muted">Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a></small>
</div>
</div>
{%endblock%}

training_proj/users/templates/users/logout.html
{%extends "users/base.html"%}
{%block content%}
<h2>You have been logged out!</h2>
<div class="border-top pt-3">
    <small class="text-muted"><a href="{% url 'login' %}">Log in again</a></small>
</div>
{%endblock%}

training_proj/users/templates/users/profile.html
{%extends "users/base.html"%}
{%load crispy_forms_tags%}
{%block content%}
<div class="content-section" style="background: #ffffff;
  padding: 10px 20px;
  border: 1px solid #dddddd;
  border-radius: 3px;
  margin-bottom: 20px;">
  <div class="media">
    <img class="rounded-circle account-img" src="{{user.profile.image.url}}" style="height: 125px;
  width: 125px;
  margin-right: 20px;
  margin-bottom: 16px;">
    <div class="media-body">
      <h2 class="account-heading" style="font-size: 2.5rem;">{{user.username}}</h2>
      <p class="text-secondary">{{user.email}}</p>
    </div>
  </div>
  <form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Profile Info</legend>
    {{u_form|crispy}}
      {{p_form|crispy}}
    </fieldset>
    <button class="btn btn-primary" type="submit">Update</button>
</form>
</div>
{%endblock%}

training_proj/users/templates/users/register.html
{%extends "users/base.html"%}
{%load crispy_forms_tags%}
{%block content%}
<form method="post">
    {%csrf_token%}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Sign Up</legend>
    {{form|crispy}}
    </fieldset>
    <button class="btn btn-primary" type="submit">Register</button>
</form>
<div class="border-top pt-3 mt-2">
    <small class="text-muted">Have an account? <a href="{% url 'login' %}">Log In</a></small>
</div>
{%endblock%}